import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import '../globals.css';

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <div>DashboardHeader</div>
      <body className={`${nunito.className}`}>
        <main className="min-h-svh">{children}</main>
      </body>
      <div>DashBoardFooter</div>
    </html>
  );
}
